package common

const S3_HOST = "HOST"
const S3_ASSESS_KEY_ID = "ACCESSKEYID"
const S3_SECRET_ACCESS_KEY = "SECRETACCESSKEY"
const S3_BUCKET_NAME = "BUCKETNAME"
const OBJECT_KEY = "OBJECTKEY"
const OUTPUT_PATH = "OUTPUTPATH"
