apiVersion: v1
kind: Service
metadata:
  name: mlserve-frontline
  labels:
    app: mlserve-frontline
spec:
  clusterIP: 10.96.173.210
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8443
      name: web
  selector:
    app: mlserve-frontline
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mlserve-frontline
spec:
  selector:
    matchLabels:
      app: mlserve-frontline # has to match .spec.template.metadata.labels
  serviceName: "mlserve-frontline"
  replicas: 3 # by default is 1
  minReadySeconds: 0 # by default is 0
  template:
    metadata:
      labels:
        app: mlserve-frontline # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mlserve-frontline
          image: quay.io/numaio/mlserve:v6
          imagePullPolicy: Always
          env:
            - name: SERVICE_NAME
              value: "mlserve-frontline"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - frontline
            - --backendurl
            - https://http-pipeline-in.mlserve.svc.cluster.local:8443/vertices/in
          ports:
            - containerPort: 8443
              name: web